### ISSUE TITLE
TBA Key not obfuscated

### ISSUE THREAD

**Issue by KennanHunter** [FRC2834/blackhawks-scouting#6]
In the security section of the readme, you make a particular point of keeping the user's TBA key safe. For reference, I found the one on the demo site in about 2 minutes by `ctrl+f`ing "X-TBA-Auth-Key". While it's understandable that securing the key would require significant project rework (more than you should do), I recommend either removing or reworking that section of the readme.

**Comment by AidanSun05** [comment]
Thanks for reporting this. You are correct on how the TBA key is visible to the user. Because Black Hawks Scouting runs entirely in the user's browser, there's no way to completely block the user from accessing the key.

Before publishing the app, I had similar thoughts about this problem. While completely hiding the key is infeasible, it's still possible to put it "deeper" within the app to deter most users from finding it. The app uses the "standard obfuscation techniques" (GitHub Secrets and `.env` files) mentioned in the readme to isolate the key from the code in the repository. Therefore, the key can only be viewed with the browser's tools, and after the app is deployed. (For comparison, many other open source scouting apps I saw at the time had the key embedded directly in the source code.)

To make sure this wouldn't violate any TBA rules, I had contacted The Blue Alliance support and asked about this situation. Part of their response was:

> There are spreadsheets and other projects that have TBA API keys published in them, and we don't see people lifting them and using them for harm. It sounds like the level of obfuscation you have would be good enough to prevent someone from lifting your key.

With all this, I made sure to emphasize security in the readme while keeping it concise. That's why that section says the key is "more difficult to find", but not "impossible to find".

Of course, if you find that part to be misleading or inaccurate, I'll be glad to change it.

**Comment by AidanSun05** [comment]
I've updated the security section of the readme; I did find it to be lacking in information. I've added some details from my comment above to clarify the intent and limitations of the key-hiding feature. If you have any feedback on the revision, let me know.
